### ISSUE TITLE
Nav bar hiding after a certain point

### ISSUE THREAD

**Issue by rodrigoibarra** [alexcican/lab#3]
Hi, I was wondering if there's a way to get the nav bar hiding after a certain amount of scroll instead of hiding it as soon as the user scrolls down. I cant really get my head around doing this.

Thanks for the awesome work btw

**Comment by alexcican** [comment]
On `<nav>` you need to add the class `.detached` by default and check with JS once it passes <a href="https://github.com/alexcican/lab/blob/gh-pages/teehan_lax_navigation/index.html#L84">detachPoint = 650</a> to hide the menu by adding the class `.invisible`.
