### ISSUE TITLE
Not working with 100% height

### ISSUE THREAD

**Issue by gracehcoote** [alexcican/lab#5]
Hi there, trying to use this plugin and I couldn't seem to get it to work, then realised that it's because the body and html tags have 100% on them, which is necessary for my site but messes up the scroll position detection part of this. Would you have any ideas for how to get around this?

**Comment by alexcican** [comment]
@gracehcoote which plugin are you referring to? I have many on this repo.

**Comment by gracehcoote** [comment]
Apologies, it's for the teehan_lax_navigation, I thought I was commenting there!

**Comment by alexcican** [comment]
@gracehcoote did you manage to find a workaround?

**Comment by gracehcoote** [comment]
@alexcican No I didn't, but in this case we actually redesigned the nav for this website to be a side nav, so it was no longer an issue! But I will be definitely using this in the future.
