### ISSUE TITLE
Uncaught TypeError: $.cookie is not a function

### ISSUE THREAD

**Issue by DamianFox** [alexcican/lab#6]
Hi.
I am trying to use your plugin, but it gives me this error: "Uncaught TypeError: $.cookie is not a function"

I have imported the plugin as such:

"< script src="http://lab.alexcican.com/set_cookies/cookie.js" type="text/javascript" ></script>
< script type="text/javascript" >
$(document).ready(function() {

  // if the cookie is true, hide the initial message and show the other one
  if ($.cookie('hide-after-click') == 'yes') {
    $('.change-message--on-click').removeClass('hide--second');
    $('.change-message--on-click').addClass('hide--first');
  }

  // add cookie to hide the first message after load (on refresh it will be hidden)
  $.cookie('hide-after-load', 'yes', {expires: 7 });

  // when clicked on “X” icon do something
  $('.close').click(function() {
    // check that “X” icon was not cliked before (hidden)
    if (!$('.change-message--on-click').is('hide--first')) {
      $('.change-message--on-click').removeClass('hide--second');
      $('.change-message--on-click').addClass('hide--first');

```
  // add cookie setting that user has clicked
  $.cookie('hide-after-click', 'yes', {expires: 7 });
}
return false;
```

  })
});
</script >" 

Where am I doing wrong?
Thanks.

**Comment by alexcican** [comment]
@DamianFox Did you include jQuery as well before this?

**Comment by DamianFox** [comment]
Yes I did. I used this:
< script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" >< /script >

**Comment by alexcican** [comment]
Everything works fine with my code. Did you:
1) Remove the spaces between `<>`? You pasted the code with spaces
`< script type="text/javascript" >`
2) Order of code should be (first to last): jQuery.js > Cookie.js > JS code
3) Some paths might be wrong. Try to store all JS external files (cookie.js) locally and run a local server to test it

If the issue persists, please send me a http://jsfiddle.net with your code.
