### ISSUE TITLE
It works only for a single page - problem

### ISSUE THREAD

**Issue by alex8123** [alexcican/lab#7]
Hi, I'm using your code but I have an issue. I'm using the code in a wordpress website. The code work fine but only in a single post. I mean if a user visit a specific post  and than visit that post again, the cookie works fine. But if the user visit another post, the cookie doesn't work anymore. 

This is the code I use:

`<script src="http://code.jquery.com/jquery-latest.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
    <script type="text/javascript" src="cookie.js"></script>
    <script type="text/JavaScript">`

`$().ready(function() {    
 if ($.cookie('hide-after-load') == 'yes') {      
                 $("#popup").hide();
             }  
  $.cookie('hide-after-load', 'yes', {expires: 7 });
    });    
    </script>`

Can you please help me?

Thank you!
G.

**Comment by nickdavis** [comment]
Hi @alex8123,

I had the same issue.

What worked for me was to use the path option to set it for all pages like this:

`$.cookie( 'hide-after-click', 'yes', {
            path: '/'
        } );`

**Comment by alex8123** [comment]
Thanks @nickdavis it works ;)
