### ISSUE TITLE
How to make the div hide always on window load

### ISSUE THREAD

**Issue by ayanize** [alexcican/lab#8]
I must say this is one of the best cookie js plugin and I am loving this. But I have an issue.

As the browser check the cookie (say **myCookie**) at first and then do actin like remove class, the problem is that the the div becomes visible for a split of a second and hides. This is actually not good for a UX.

I would like it to hide or remove forever (or least not visible on page load at all) when the close button is clicked. Is it possible?

Many thanks

**Comment by alexcican** [comment]
@ayanize you could do it differently: 
Hide the DIV by default (CSS) and upon loading page check if cookie exists = keep it hidden. If it doesn’t exist then show it (remove CSS class).

**Comment by ayanize** [comment]
@alexcican . Hi, I have figured this out. I am sorry. I should have updated this tread. Here is how I went.

**JS**

 ```
if ($.cookie('myCookie') == null) {
        $('#cookie-div').addClass('hascookie');
		$('.hascookie').slideDown(800);
	  }
	
     $('.cookie-close').click(function() {
        if (!$('#cookie-div').is('hascookie')) {
          $('#cookie-div').removeClass('hascookie');
		  $('#cookie-div').slideUp(800);
		$.cookie('myCookie', 'yes', {expires: 1 });
        }
        return false;
      }); 
```

**CSS**

```
#cookie-div.hascookie{
display: block;
}
```

Thanks once again for your wonderful piece of code.

**Comment by alexcican** [comment]
Glad you solved it! :)
